server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java-09-springboot
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Cuong211998
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: java-09-springboot